# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x0e\n\x0c\x45mptyMessage\"7\n\x12RequsetVoteMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\"6\n\x14\x41ppendEntriesMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\" \n\x0eSuspendMessage\x12\x0e\n\x06period\x18\x01 \x01(\x05\"0\n\x0fSuccessResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"-\n\x0eLeaderResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t2\xd7\x01\n\rServerService\x12\x34\n\x0bRequsetVote\x12\x13.RequsetVoteMessage\x1a\x10.SuccessResponse\x12\x38\n\rAppendEntries\x12\x15.AppendEntriesMessage\x1a\x10.SuccessResponse\x12+\n\tGetLeader\x12\r.EmptyMessage\x1a\x0f.LeaderResponse\x12)\n\x07Suspend\x12\x0f.SuspendMessage\x1a\r.EmptyMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=14
  _EMPTYMESSAGE._serialized_end=28
  _REQUSETVOTEMESSAGE._serialized_start=30
  _REQUSETVOTEMESSAGE._serialized_end=85
  _APPENDENTRIESMESSAGE._serialized_start=87
  _APPENDENTRIESMESSAGE._serialized_end=141
  _SUSPENDMESSAGE._serialized_start=143
  _SUSPENDMESSAGE._serialized_end=175
  _SUCCESSRESPONSE._serialized_start=177
  _SUCCESSRESPONSE._serialized_end=225
  _LEADERRESPONSE._serialized_start=227
  _LEADERRESPONSE._serialized_end=272
  _SERVERSERVICE._serialized_start=275
  _SERVERSERVICE._serialized_end=490
# @@protoc_insertion_point(module_scope)
